# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-partuuid/dd0eb9b7-c9c2-4b64-adc6-d1f34bf819f4";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-partuuid/dd0eb9b7-c9c2-4b64-adc6-d1f34bf819f4";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-partuuid/dd0eb9b7-c9c2-4b64-adc6-d1f34bf819f4";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-partuuid/41ea3b01-d7e8-4397-8be2-fbaedc2a2bef";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/disk/c" = {
    device = "/dev/disk/by-partuuid/9765a1d1-ff36-4e38-a500-9da33530a6b8";
    fsType = "ntfs";
    options = [
      "ro"
      "nofail"
    ];
  };

  fileSystems."/disk/d" = {
    device = "/dev/disk/by-partuuid/5d75ab99-cf6a-4a0f-8d60-5b09bda5fa9d";
    fsType = "ntfs";
    options = [
      "nofail"
    ];
  };

  fileSystems."/disk/f" = {
    device = "/dev/disk/by-partuuid/9c5003a5-62cf-44d2-94f2-9c18041c22f1";
    fsType = "ntfs";
    options = [
      "nofail"
    ];
  };

  fileSystems."/disk/e" = {
    device = "/dev/disk/by-partuuid/80636dfb-26d7-45aa-8794-34a02ec1bc0c";
    fsType = "ntfs";
    options = [
      "nofail"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
